// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion
const { inject } = require("@vercel/analytics");

inject();
const lightCodeTheme = require("prism-react-renderer/themes/github");
const darkCodeTheme = require("prism-react-renderer/themes/dracula");

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Codust",
  tagline: "Explore Modern Web Development in Depth",
  favicon: "img/SIR_Logo.png",

  // Set the production url of your site here
  url: "https://codust-tutorial.vercel.app/",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "Codust", // Usually your GitHub org/user name.
  projectName: "Codust Tutorial", // Usually your repo name.

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
        },
        blog: {
          showReadingTime: true,
        },
        theme: {
          customCss: require.resolve("./src/css/custom.css"),
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/docusaurus-social-card.jpg",
      navbar: {
        title: "Codust ",
        logo: {
          alt: "SIR Logo",
          src: "img/SIR_Logo.png",
        },
        items: [
          {
            type: "docSidebar",
            sidebarId: "tutorialSidebar",
            position: "left",
            label: "Courses",
          },
          { to: "/blog", label: "Blog", position: "left" },
          { to: "/assignment", label: "Assignment", position: "left" },

          {
            type: "localeDropdown",
          },
          {
            href: "https://github.com/Codust-SIR",
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Docs",
            items: [
              {
                label: "Tutorial",
                to: "/docs/intro",
              },
            ],
          },
          {
            title: "Community",
            items: [
              {
                label: "Twitter",
                href: "https://twitter.com/SolidarityInit1",
              },
              {
                label: "WhatsApp",
                href: "https://chat.whatsapp.com/F4kTZOgxoiM2AD475drWqS",
              },
            ],
          },
          {
            title: "More",
            items: [
              {
                label: "Blog",
                to: "/blog",
              },
              {
                label: "GitHub",
                href: "https://github.com/Codust-SIR",
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Solidarity Initiative for Refugees`,
      },
      prism: {
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      },
      algolia: {
        // The application ID provided by Algolia
        appId: "X7F7HPFI1C",

        // Public API key: it is safe to commit it
        apiKey: "b7f66f7ef62879921d9bde3b2e516160",

        indexName: "codust-tutorial",
      },
      docsSidebars: {
        // Display the "Basic" sidebar when on a page in the "Basic" section
        basic: [
          {
            type: "autogenerated",
            dirName: "./docs/basic-ict",
          },
        ],
        // Display the "Advanced" sidebar when on a page in the "Advanced" section
        advanced: [
          {
            type: "autogenerated",
            dirName: "./docs/advanced-ict",
          },
        ],
      },
    }),
};

module.exports = config;
